vich_uploader:
    db_driver: orm

    mappings:
        pictures_destination:
            uri_prefix: /images/pictures_destinations
            upload_destination: '%kernel.project_dir%/public/images/pictures_destinations'
            namer: 
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'name'}

        pictures_spacecrafts:
            uri_prefix: /images/pictures_spacecrafts
            upload_destination: '%kernel.project_dir%/public/images/pictures_spacecrafts'
            namer: 
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'name'}

        pictures_spacecrafts_brands:
            uri_prefix: /images/pictures_spacecrafts/pictures_spacecrafts_brands
            upload_destination: '%kernel.project_dir%/public/images/pictures_spacecrafts/pictures_spacecrafts_brands'
            namer: 
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'name'}
        


